#!/usr/bin/python3

import os, sys
import matplotlib.pyplot as plt
import numpy as np

# Refer to https://github.com/jiaaro/pydub/blob/master/API.markdown for the API documentation
from pydub import AudioSegment

# Read the file
audio = AudioSegment.from_mp3(sys.argv[1])
print("Frame rate:", audio.frame_rate)

# Refer to https://en.wikipedia.org/wiki/DBFS (DeciBels relative to Full Scale)
print("Max dBFS:", audio.max_dBFS)

# Get the due numpy array
samples = np.frombuffer(audio.raw_data, dtype=np.int16)
nSamples = samples.shape[0]

# We assume 2 channels, and reshape the array to 2 columns
samples = samples.reshape(nSamples//2, 2, order="C")

def is_normalized(audio):
    fraction = audio.max / audio.max_possible_amplitude

    if fraction < 0.9:
        return False
    else:
        return True

print(is_normalized(audio))

# plt.figure()
# plt.plot(samples[:,0])
# plt.show()
