#!/bin/bash

files="";
nfiles=0;

# Filter *~ from $@
for i in $@; do
	lastchar=${i:(-1):1};
	if [[ $lastchar != "~" ]]; then
		files="$files $i";
		nfiles=$((nfiles + 1));
	fi
done

# Transform files in an array
files=($files);

if [ $nfiles == 0 ]; then
	vim;
elif [ $nfiles == 1 ]; then
	vim ${files[0]};
elif [ $nfiles == 2 ]; then
	vim ${files[1]} -c ":vsp ${files[0]}";
elif [ $nfiles == 3 ]; then
	vim ${files[2]} -c ":sp ${files[1]}" -c ":vertical topleft split ${files[0]}";
else
	echo "More than 3 files isn't supported.";
fi
