#!/bin/bash

# Help message
helpmsg=\
"Usage: $0 [arguments]

Where [arguments] can be:
	home         - ssh to your home workstation
	lasdpc       - ssh to your lasdpc workstation
	halley       - ssh to cluster Halley
";
if [ $# -eq 0 ]; then
	echo "$helpmsg"
	exit 0;
fi

# Actions
case $1 in
	home)
		ssh -i "$HOME/.ssh/passless" mathjs@`elf-ip home` ;;
	lasdpc)
		ssh -i "$HOME/.ssh/passless" mathjs@localhost -p 10000 ;;
	halley)
		ssh mhjs@halley.lasdpc.icmc.usp.br -p 22200 ;;
esac;
