#!/bin/bash

# Help message
helpmsg=\
"Usage: $0 [arguments]

Where [arguments] can be:
	home         - ssh to your home workstation
	lasdpc       - ssh to your lasdpc workstation
	halley       - ssh to cluster Halley
	web          - ssh to your webpage server
";
if [ $# -eq 0 ]; then
	echo "$helpmsg"
	exit 0;
fi

# Actions
case $1 in
	home)
		ssh -i "$HOME/.ssh/passless" mathjs@`elf-ip home` ;;
	lasdpc)
		ssh -i "$HOME/.ssh/passless" mathjs@localhost -p 10000 ;;
	halley)
		ssh mhjs@andromeda.lasdpc.icmc.usp.br -p 2210 ;;
	web)
		ssh 20590-2942@gate.milesweb.cloud -p 3022 ;;
esac;
