#!/bin/bash

# Help message
helpmsg=\
"Usage: $0 [arguments]

Where [arguments] can be:
	home         - ssh to your home workstation
	lasdpc       - ssh to your lasdpc workstation
";
if [ $# -eq 0 ]; then
	echo "$helpmsg"
	exit 0;
fi

# Actions
case $1 in
	home)
		ssh mathjs@`elf-ip home` ;;
	lasdpc)
		ssh mathjs@localhost -p 10000 ;;
esac;
