#!/bin/bash

# Help message
helpmsg=\
"Usage: $0 [arguments]

Where [arguments] can be:
	home         - ip of your home workstation
";
if [ $# -eq 0 ]; then
	echo "$helpmsg"
	exit 0;
fi

# Actions
case $1 in
	home)
		ip=$( curl -m 10 -L https://mjsaldanha.com/myip 2> /dev/null ); # Get from website
		if [ "$?" != "0" ]; then
			echo "Failed to get IP from website. Using previously saved one."
			ip=$( cat ~/Warehouse/.elf-ip-home 2> /dev/null );  # Get from file
		else
			echo $ip > ~/Warehouse/.elf-ip-home; # Save to file
		fi

		echo $ip; # Print to stdin
		;;
esac;
