#!/bin/bash

myip="localhost"

# Looks up our local IP
function ip_lookup {
	dig +short myip.opendns.com @resolver1.opendns.com;
}

function test_ssh {
	echo " "
	echo "Checking PORT 22 availability on $1"
	
	# Run in background
	{ echo " " | telnet $1 22 &> /dev/null; } &
	
	# Sleep 2 seconds
	sleep 2

	# Try to kill
	pid="$!"
	kill -9 $pid &> /dev/null
	retval="$?"
	
	echo "Result: " $retval

	if [ $retval -eq "1" ]; then
		# If failed, then ssh is working
		return 0
	else
		return 1
	fi
}


# Eternal loop
while [ 1 ]; do

	# Check IP difference
	while [ 1 ]; do
		# Get current ip
		trial=$( ip_lookup );
		warn=false;

		# Compare with last sent ip
		if [ "$myip" != "$trial" ]; then
			myip="$trial";
			echo "Difference Detected. New IP = $myip";
			break;
		fi

		for i in $( seq 6 ); do
			test_ssh $myip

			if [ $? -eq "0" ]; then
				warn=false
			else
				warn=true
			fi

			if [ "$warn" = true ]; then
				notify-send "PORT 22 needs fixing."
				echo "==== PORT 22 IS NOT AVAILABLE. FIX IT. ===="
			else
				echo "Port 22 is OK."
			fi

			sleep 58
		done
	done

	# Send different, new IP. First try HTTP, then HTTPS
	res=$( curl -s -d ip="$myip" mjsaldanha.com/myip );
	echo "HTTP response: " $res;
	if [[ "$res" != "Ok" ]]; then
		res=$( curl -s --proto-default https -d ip="$myip" mjsaldanha.com/myip );
		echo "HTTPS response: " $res;
	fi

	# If neither protocol works
	if [[ "$res" != "Ok" ]]; then
		echo "Error sending IP!!!";
	fi

	echo
done
