#!/bin/bash

remote_dir="~/Shared/lasdpc"

# Help message
helpmsg=\
"Usage: $0 [arguments]

Where [arguments] can be (in any order):
	home send         - backup to your home workstation
	home send delete  - backup to your home workstation, deleting extraneous files
	home get          - get files from home workstation
	local send        - backup to local off-VM workstation, deleting extraneous files
	local send delete - backup to local off-VM workstation, deleting extraneous files
";
if [ $# -eq 0 ]; then
	echo "$helpmsg"
	exit 0;
fi


arghome=false
arglocal=false
argsend=false
argget=false
argdelete=false

# ==========================
# Parse User Arguments
# ==========================
while [[ "$#" > 0 ]]; do case $1 in
	home)
		arghome=true;;
	local)
		arglocal=true;;
	send)
		argsend=true;;
	get)
		argget=true;;
	delete)
		argdelete=true;;
esac; shift; done;

# Some pre-processing
myip=""
localip="10.0.0.100"
if [ $arghome = "true" ]; then
	myip=$(elf-ip home);
fi


# ==========================
# Execute functionality
# ==========================
if   [[ $arghome = "true" && $argsend = "true" && $argdelete = "false" ]]; then
	echo "home send";
	rsync -avz ~/ mathjs@$myip:$remote_dir;
elif [[ $arghome = "true" && $argsend = "true" && $argdelete = "true" ]]; then
	echo "home send delete";
	rsync -avz --delete ~/ mathjs@$myip:$remote_dir;
elif [[ $arghome = "true" && $argget = "true" && $argdelete = "true" ]]; then
	echo "home get";
	rsync -avz mathjs@$myip:$remote_dir ~/;
elif [[ $arglocal = "true" && $argsend = "true" && $argdelete = "false" ]]; then
	echo "local send";
	rsync -avz ~/ mhjs@$localip:$remote_dir;
elif [[ $arglocal = "true" && $argsend = "true" && $argdelete = "true" ]]; then
	echo "local send delete";
	rsync -avz --delete ~/ mhjs@$localip:$remote_dir;
fi

